### ISSUE TITLE
Problems during NLS translation...

### ISSUE THREAD

**Issue by sebras** [FDOS/label#11]
There is a [problem](https://github.com/FDOS/label/blob/master/src/label.c#L712) with translating this message since the expected keyboard input is Y or N for Yes and No. This matches badly when LABEL is translated into Swedish where a Y/N question should be J/N for Ja and Nej.

Please consider allowing for translation of the input keys at https://github.com/FDOS/label/blob/master/src/label.c#L715 and https://github.com/FDOS/label/blob/master/src/label.c#L717

**Comment by andrewbird** [comment]
Thanks for the report, I'm looking at a solution today.
