### ISSUE TITLE
Thoughts about moving prf.c to separate submodule

### ISSUE THREAD

**Issue by andrewbird** [FDOS/label#14]
I see that many FDOS projects (choice, label, mem, more, xcopy etc) use a minimal printf replacement called prf.c and there are also others like move and sort that could use it too. I'm thinking it would be a good idea to split this out into a submodule to make it more maintainable just like we did with kitten. Do you think that's a good idea? If so I'd like to use the version from here as it has the tweaks necessary to compile with ia16gcc, shall I call it `tnyprntf`?

I'm converting the following repos, and have pushed as indicated by the tick.

- [x] choice
- [x] fc
- [x] find
- [x] label
- [x] more
- [x] move
- [x] sort
- [ ] xcopy

**Comment by PerditionC** [comment]
Sounds good to me

**Comment by andrewbird** [comment]
Great, thanks. I'll work on that now.

**Comment by andrewbird** [comment]
Perhaps you could move this issue to FDOS/tnyprntf as it doesn't really belong here?
