### ISSUE TITLE
Translations required, please!

### ISSUE THREAD

**Issue by andrewbird** [FDOS/label#3]
Label now has translation support, but needs the strings for each language.

**Comment by cardpuncher** [comment]
Hey,

Thank you for making LABEL translatable. I'm attaching French & Turkish translations, but please note that @shidel keeps a repository of all translations for FreeDOS at <https://github.com/shidel/fd-nls>. Had this been announced there, I would have translated it sooner. In fact, I stumbled upon this bug report completely by chance. If there is other stuff I missed, please yell at me.

[LABEL-fr-tr.zip](https://github.com/FDOS/label/files/6446225/LABEL-fr-tr.zip)

Also, @bitigchi feel free to check the Turkish version :) I translated "volume label" as "bölüm etiketi" but I'm not entirely satisfied with it (the translation is short).

**Comment by bitigchi** [comment]
@cardpuncher, thank you very much for your work! Translations are good, I just made small changes to make them consistent with the rest of the DOS utilities. I've also attached a UTF-8 version as a base file to make sure everything can be restored if the encoding goes awry somehow.

(@andrewbird, sorry, I am too exhausted from work to make a proper pull request, hope .zip file is okay :D)

[label-tr.zip](https://github.com/FDOS/label/files/6446386/label-tr.zip)

**Comment by andrewbird** [comment]
Thanks, I'll update my PR with it later this evening.

**Comment by PerditionC** [comment]
I'm working on setting up my development environment (formally I used windows XP, so I'm updating it to windows 10 and Debian Linux), so I can publish new releases with latest translation work and any other updates (all programs in FDOS without upstream maintainers)

**Comment by PerditionC** [comment]
I appreciate all the work done for translations, thank you all.

**Comment by andrewbird** [comment]
@bitigchi the encoding seems fine.

**Comment by andrewbird** [comment]
Closing this as all translations should go to https://github.com/shidel/fd-nls (ideally in UTF-8 format)
